
package org.onvif.ver10.events.wsdl;

import jakarta.xml.ws.WebFault;
import org.oasis_open.docs.wsn.b_2.InvalidTopicExpressionFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidTopicExpressionFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class InvalidTopicExpressionFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -6565487645210504217L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidTopicExpressionFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidTopicExpressionFault(String message, InvalidTopicExpressionFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidTopicExpressionFault(String message, InvalidTopicExpressionFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.InvalidTopicExpressionFaultType
     */
    public InvalidTopicExpressionFaultType getFaultInfo() {
        return faultInfo;
    }

}
