
package org.onvif.ver10.events.wsdl;

import jakarta.xml.ws.WebFault;
import org.oasis_open.docs.wsn.b_2.NotifyMessageNotSupportedFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotifyMessageNotSupportedFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class NotifyMessageNotSupportedFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 3101669838872502349L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotifyMessageNotSupportedFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NotifyMessageNotSupportedFault(String message, NotifyMessageNotSupportedFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NotifyMessageNotSupportedFault(String message, NotifyMessageNotSupportedFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.NotifyMessageNotSupportedFaultType
     */
    public NotifyMessageNotSupportedFaultType getFaultInfo() {
        return faultInfo;
    }

}
