
package org.onvif.ver10.events.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PullMessagesFaultResponse", targetNamespace = "http://www.onvif.org/ver10/events/wsdl")
public class PullMessagesFaultResponse_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -6561909317755474736L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PullMessagesFaultResponse faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PullMessagesFaultResponse_Exception(String message, PullMessagesFaultResponse faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PullMessagesFaultResponse_Exception(String message, PullMessagesFaultResponse faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.onvif.ver10.events.wsdl.PullMessagesFaultResponse
     */
    public PullMessagesFaultResponse getFaultInfo() {
        return faultInfo;
    }

}
