
package org.onvif.ver10.events.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PullPointSubscriptionService", targetNamespace = "http://www.onvif.org/ver10/events/wsdl", wsdlLocation = "classpath:wsdl/eventProxy.wsdl")
public class PullPointSubscriptionService
    extends Service
{

    private final static URL PULLPOINTSUBSCRIPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PULLPOINTSUBSCRIPTIONSERVICE_EXCEPTION;
    private final static QName PULLPOINTSUBSCRIPTIONSERVICE_QNAME = new QName("http://www.onvif.org/ver10/events/wsdl", "PullPointSubscriptionService");

    static {
        PULLPOINTSUBSCRIPTIONSERVICE_WSDL_LOCATION = PullPointSubscriptionService.class.getResource("classpath:wsdl/eventProxy.wsdl");
        WebServiceException e = null;
        if (PULLPOINTSUBSCRIPTIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'classpath:wsdl/eventProxy.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PULLPOINTSUBSCRIPTIONSERVICE_EXCEPTION = e;
    }

    public PullPointSubscriptionService() {
        super(__getWsdlLocation(), PULLPOINTSUBSCRIPTIONSERVICE_QNAME);
    }

    public PullPointSubscriptionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PULLPOINTSUBSCRIPTIONSERVICE_QNAME, features);
    }

    public PullPointSubscriptionService(URL wsdlLocation) {
        super(wsdlLocation, PULLPOINTSUBSCRIPTIONSERVICE_QNAME);
    }

    public PullPointSubscriptionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PULLPOINTSUBSCRIPTIONSERVICE_QNAME, features);
    }

    public PullPointSubscriptionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PullPointSubscriptionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PullPointSubscription
     */
    @WebEndpoint(name = "PullPointSubscriptionServicePort")
    public PullPointSubscription getPullPointSubscriptionServicePort() {
        return super.getPort(new QName("http://www.onvif.org/ver10/events/wsdl", "PullPointSubscriptionServicePort"), PullPointSubscription.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PullPointSubscription
     */
    @WebEndpoint(name = "PullPointSubscriptionServicePort")
    public PullPointSubscription getPullPointSubscriptionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.onvif.org/ver10/events/wsdl", "PullPointSubscriptionServicePort"), PullPointSubscription.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PULLPOINTSUBSCRIPTIONSERVICE_EXCEPTION!= null) {
            throw PULLPOINTSUBSCRIPTIONSERVICE_EXCEPTION;
        }
        return PULLPOINTSUBSCRIPTIONSERVICE_WSDL_LOCATION;
    }

}
