
package org.onvif.ver10.events.wsdl;

import jakarta.xml.ws.WebFault;
import org.oasis_open.docs.wsrf.r_2.ResourceUnknownFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ResourceUnknownFault", targetNamespace = "http://docs.oasis-open.org/wsrf/r-2")
public class ResourceUnknownFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 8337697347834653610L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ResourceUnknownFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ResourceUnknownFault(String message, ResourceUnknownFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ResourceUnknownFault(String message, ResourceUnknownFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsrf.r_2.ResourceUnknownFaultType
     */
    public ResourceUnknownFaultType getFaultInfo() {
        return faultInfo;
    }

}
