
package org.onvif.ver10.events.wsdl;

import java.util.concurrent.Future;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;
import org.oasis_open.docs.wsn.b_2.Renew;
import org.oasis_open.docs.wsn.b_2.RenewResponse;
import org.oasis_open.docs.wsn.b_2.Unsubscribe;
import org.oasis_open.docs.wsn.b_2.UnsubscribeResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubscriptionManager", targetNamespace = "http://docs.oasis-open.org/wsn/bw-2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class,
    org.oasis_open.docs.wsn.b_2.ObjectFactory.class,
    org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class,
    org.oasis_open.docs.wsn.t_1.ObjectFactory.class,
    org.oasis_open.docs.wsrf.r_2.ObjectFactory.class,
    org.w3._2005._08.addressing.ObjectFactory.class
})
public interface SubscriptionManager {


    /**
     * 
     * @param renewRequest
     * @return
     *     returns jakarta.xml.ws.Response<org.oasis_open.docs.wsn.b_2.RenewResponse>
     */
    @WebMethod(operationName = "Renew", action = "http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/RenewRequest")
    public Response<RenewResponse> renewAsync(
        @WebParam(name = "Renew", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "RenewRequest")
        Renew renewRequest);

    /**
     * 
     * @param renewRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "Renew", action = "http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/RenewRequest")
    public Future<?> renewAsync(
        @WebParam(name = "Renew", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "RenewRequest")
        Renew renewRequest,
        @WebParam(name = "RenewResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RenewResponse> asyncHandler);

    /**
     * 
     * @param renewRequest
     * @return
     *     returns org.oasis_open.docs.wsn.b_2.RenewResponse
     * @throws ResourceUnknownFault
     * @throws UnacceptableTerminationTimeFault
     */
    @WebMethod(operationName = "Renew", action = "http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/RenewRequest")
    @WebResult(name = "RenewResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "RenewResponse")
    public RenewResponse renew(
        @WebParam(name = "Renew", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "RenewRequest")
        Renew renewRequest)
        throws ResourceUnknownFault, UnacceptableTerminationTimeFault
    ;

    /**
     * 
     * @param unsubscribeRequest
     * @return
     *     returns jakarta.xml.ws.Response<org.oasis_open.docs.wsn.b_2.UnsubscribeResponse>
     */
    @WebMethod(operationName = "Unsubscribe", action = "http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/UnsubscribeRequest")
    public Response<UnsubscribeResponse> unsubscribeAsync(
        @WebParam(name = "Unsubscribe", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "UnsubscribeRequest")
        Unsubscribe unsubscribeRequest);

    /**
     * 
     * @param asyncHandler
     * @param unsubscribeRequest
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "Unsubscribe", action = "http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/UnsubscribeRequest")
    public Future<?> unsubscribeAsync(
        @WebParam(name = "Unsubscribe", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "UnsubscribeRequest")
        Unsubscribe unsubscribeRequest,
        @WebParam(name = "UnsubscribeResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<UnsubscribeResponse> asyncHandler);

    /**
     * 
     * @param unsubscribeRequest
     * @return
     *     returns org.oasis_open.docs.wsn.b_2.UnsubscribeResponse
     * @throws ResourceUnknownFault
     * @throws UnableToDestroySubscriptionFault
     */
    @WebMethod(operationName = "Unsubscribe", action = "http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/UnsubscribeRequest")
    @WebResult(name = "UnsubscribeResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "UnsubscribeResponse")
    public UnsubscribeResponse unsubscribe(
        @WebParam(name = "Unsubscribe", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "UnsubscribeRequest")
        Unsubscribe unsubscribeRequest)
        throws ResourceUnknownFault, UnableToDestroySubscriptionFault
    ;

}
