
package org.onvif.ver10.events.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubscriptionManagerService", targetNamespace = "http://www.onvif.org/ver10/events/wsdl", wsdlLocation = "classpath:wsdl/eventProxy.wsdl")
public class SubscriptionManagerService
    extends Service
{

    private final static URL SUBSCRIPTIONMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBSCRIPTIONMANAGERSERVICE_EXCEPTION;
    private final static QName SUBSCRIPTIONMANAGERSERVICE_QNAME = new QName("http://www.onvif.org/ver10/events/wsdl", "SubscriptionManagerService");

    static {
        SUBSCRIPTIONMANAGERSERVICE_WSDL_LOCATION = SubscriptionManagerService.class.getResource("classpath:wsdl/eventProxy.wsdl");
        WebServiceException e = null;
        if (SUBSCRIPTIONMANAGERSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'classpath:wsdl/eventProxy.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SUBSCRIPTIONMANAGERSERVICE_EXCEPTION = e;
    }

    public SubscriptionManagerService() {
        super(__getWsdlLocation(), SUBSCRIPTIONMANAGERSERVICE_QNAME);
    }

    public SubscriptionManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBSCRIPTIONMANAGERSERVICE_QNAME, features);
    }

    public SubscriptionManagerService(URL wsdlLocation) {
        super(wsdlLocation, SUBSCRIPTIONMANAGERSERVICE_QNAME);
    }

    public SubscriptionManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBSCRIPTIONMANAGERSERVICE_QNAME, features);
    }

    public SubscriptionManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriptionManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriptionManager
     */
    @WebEndpoint(name = "SubscriptionManagerServicePort")
    public SubscriptionManager getSubscriptionManagerServicePort() {
        return super.getPort(new QName("http://www.onvif.org/ver10/events/wsdl", "SubscriptionManagerServicePort"), SubscriptionManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriptionManager
     */
    @WebEndpoint(name = "SubscriptionManagerServicePort")
    public SubscriptionManager getSubscriptionManagerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.onvif.org/ver10/events/wsdl", "SubscriptionManagerServicePort"), SubscriptionManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBSCRIPTIONMANAGERSERVICE_EXCEPTION!= null) {
            throw SUBSCRIPTIONMANAGERSERVICE_EXCEPTION;
        }
        return SUBSCRIPTIONMANAGERSERVICE_WSDL_LOCATION;
    }

}
