
package org.onvif.ver10.events.wsdl;

import jakarta.xml.ws.WebFault;
import org.oasis_open.docs.wsn.b_2.TopicExpressionDialectUnknownFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TopicExpressionDialectUnknownFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class TopicExpressionDialectUnknownFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 8149633345932807947L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TopicExpressionDialectUnknownFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TopicExpressionDialectUnknownFault(String message, TopicExpressionDialectUnknownFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TopicExpressionDialectUnknownFault(String message, TopicExpressionDialectUnknownFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.TopicExpressionDialectUnknownFaultType
     */
    public TopicExpressionDialectUnknownFaultType getFaultInfo() {
        return faultInfo;
    }

}
