
package org.onvif.ver10.events.wsdl;

import jakarta.xml.ws.WebFault;
import org.oasis_open.docs.wsn.b_2.UnacceptableInitialTerminationTimeFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnacceptableInitialTerminationTimeFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnacceptableInitialTerminationTimeFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1631406212440862333L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnacceptableInitialTerminationTimeFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UnacceptableInitialTerminationTimeFault(String message, UnacceptableInitialTerminationTimeFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnacceptableInitialTerminationTimeFault(String message, UnacceptableInitialTerminationTimeFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.UnacceptableInitialTerminationTimeFaultType
     */
    public UnacceptableInitialTerminationTimeFaultType getFaultInfo() {
        return faultInfo;
    }

}
