
package org.onvif.ver10.events.wsdl;

import jakarta.xml.ws.WebFault;
import org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnacceptableTerminationTimeFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnacceptableTerminationTimeFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -8970887116817106088L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnacceptableTerminationTimeFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UnacceptableTerminationTimeFault(String message, UnacceptableTerminationTimeFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnacceptableTerminationTimeFault(String message, UnacceptableTerminationTimeFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType
     */
    public UnacceptableTerminationTimeFaultType getFaultInfo() {
        return faultInfo;
    }

}
