
package org.onvif.ver10.events.wsdl;

import jakarta.xml.ws.WebFault;
import org.oasis_open.docs.wsn.b_2.UnrecognizedPolicyRequestFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnrecognizedPolicyRequestFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnrecognizedPolicyRequestFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -7174216683223465375L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnrecognizedPolicyRequestFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UnrecognizedPolicyRequestFault(String message, UnrecognizedPolicyRequestFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnrecognizedPolicyRequestFault(String message, UnrecognizedPolicyRequestFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.UnrecognizedPolicyRequestFaultType
     */
    public UnrecognizedPolicyRequestFaultType getFaultInfo() {
        return faultInfo;
    }

}
